### ISSUE TITLE
DeskBand example crashes explorer.exe

### ISSUE THREAD

**Issue by hasaranga** [microsoft/Windows-classic-samples#136]
Deskband sample crashes explorer.exe after few minutes of use.
built with VS2019 v16.5.4.
tested on Win10 1909.

The deskband of this tool works fine : https://batterybarpro.com
That means win10 still supports deskband objects right? If so, why the sample crashes?

**Comment by PeterBeckwith** [comment]
The sample owner found the issue.  The explanation and a fix are below:

The DLL is getting unloaded due to DllCanUnloadNow saying there are no outstanding references – there are though, so once the DLL is unloaded, the WndProc of the deskband window is still called and that causes the crash. The fix is to have the CDeskBand class increment and decrement references to the global DLL reference count – that will cause DllCanUnloadNow to prevent the deskband DLL from being unloaded when a deskband exists.

See revised code for DeskBand.cpp in:

https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/3663de60-be1d-4a90-aca6-1b88b7a0a41a/windows-7-explorer-periodically-crashes-when-a-deskband-is-enabled?forum=windowssdk

**Comment by PeterBeckwith** [comment]
For the sake of completeness, and in case the link goes dead, the necessary changes are shown here:
```
// DeskBand.cpp

CDeskBand::CDeskBand() :
    m_cRef(1), m_pSite(NULL), m_fHasFocus(FALSE), m_fIsDirty(FALSE), m_dwBandID(0), m_hwnd(NULL), m_hwndParent(NULL)
{
    InterlockedIncrement(&g_cDllRef);
}

CDeskBand::~CDeskBand()
{
    if (m_pSite)
    {
        m_pSite->Release();
    }
    InterlockedDecrement(&g_cDllRef);
}
```

**Comment by hasaranga** [comment]
Thanks! The bug was found in 2009 according to your link. But why they didn't update the code?

**Comment by oldnewthing** [comment]
Well, to be fair, this repo didn't exist in 2009.

**Comment by hasaranga** [comment]
Yes, but the sample code did exist right? :-)

**Comment by oldnewthing** [comment]
True, but there was nowhere to submit the fix. Fix will be in the next refresh.
